name: After all workflows check
description: Checks if all required workflows have completed successfully for a given commit SHA

inputs:
  jq-pre-filter:
    type: string
    default: >-
      {workflow_runs: [.workflow_runs[] | select(.name | IN(\($wf_names))) | {name, id, conclusion, created_at, status}]}
  max-results:
    type: number
    default: 200
  repo:
    type: string
    default: ${{ github.repository }}
  sha:
    type: string
    required: true
    description: Commit SHA to check
  workflows:
    type: string
    required: true
    description: JSON array of required workflow names
  token:
    type: string
    required: false
    default: ${{ github.token }}
    description: GitHub token
  template-script:
    type: string
    default: |
      SCRIPT_JQ='\($jq)'
      MAX_PAGES='\($max_pages)'
      HEAD_SHA='\(.sha)'
      PER_PAGE='\(.per_page)'
      REPO='\(.repo)'
      OUTPUT=\"[]\"
      for PAGE in $(seq 1 "${MAX_PAGES}"); do
          PAGE_OUTPUT=$(gh api --jq \"${SCRIPT_JQ}\" \"/repos/${REPO}/actions/runs?page=${PAGE}&head_sha=${HEAD_SHA}&status=completed&per_page=${PER_PAGE}\")
          OUTPUT=$(jq -c --argjson a \"$OUTPUT\" --argjson b \"$PAGE_OUTPUT\" '$a+$b')
      done

outputs:
  status:
    value: ${{ steps.check-workflows.outputs.output }}
    description: Full status JSON object with details for each workflow
  continue:
    value: ${{ fromJSON(steps.check-workflows.outputs.output).continue }}
    description: "'true' or 'false' - whether all required workflows passed"
  run-ids:
    value: ${{ fromJSON(steps.check-workflows.outputs.output)['run-ids'] }}
    description: JSON object mapping workflow names to run IDs


runs:
  using: composite
  steps:
  - uses: envoyproxy/toolshed/gh-actions/jq@actions-v0.3.35
    id: workflows
    with:
      options: -sRc
      input: ${{ inputs.workflows }}
      filter: |
        .
        | split("\n")
        | map(select(length > 0))
  - uses: envoyproxy/toolshed/gh-actions/bson@actions-v0.3.35
    id: check-workflows
    env:
      GH_TOKEN: ${{ inputs.token }}
    with:
      input: |
        per_page: ${{ inputs.max-results }}
        repo: ${{ inputs.repo }}
        sha: ${{ inputs.sha }}
        workflows: ${{ steps.workflows.outputs.value }}
      input-format: yaml
      filter: |
        .
        | "2" as $page
        | (.workflows | tojson | .[1:-1]) as $wf_names
        | "${{ inputs.jq-pre-filter }}" as $jq
        | ("${{ inputs.template-script }}" | bash::output)
      result-format: json
      result-filter-options: "-c"
      result-filter: |
        . as $data
        | ${{ steps.workflows.outputs.value }} as $workflows
        | .workflow_runs as $runs
        | {continue: true, "run-ids": {}, status: {}} as $init
        | reduce $workflows[] as $name ($init;
            ([$runs[] | select(.name == $name)] | sort_by(.created_at) | last) as $run
            | if $run then
                .status[$name] = {id: $run.id, conclusion: $run.conclusion}
                | if $run.conclusion == "success" then
                    .["run-ids"][$name] = $run.id
                  else
                    .continue = false
                  end
              else
                .continue = false
              end)
        | {continue: (.continue | tostring),
           "run-ids": (."run-ids" | tojson),
           status: (.status | tojson)}
